version: 2

defaults: &defaults
  docker:
    - image: cimg/openjdk:11.0.18
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  unit-tests:
    <<: *defaults
    steps:
      - checkout
      - run: java --version
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Run the unit tests
          command: bundle exec fastlane test
      - store_artifacts:
          path: app/build/reports
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
  build:
    working_directory: ~/code
    docker:
      - image: cimg/openjdk:11.0.18
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Assemble a debug apk
          command: bundle exec fastlane assemble_debug
      - run:
          name: Assemble an android test apk
          command: bundle exec fastlane assemble_android_test
      - run:
          name: Build the aab file
          command: bundle exec fastlane build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results