version: 2.1

#defaults: &defaults
#  docker:
#    - image: cimg/openjdk:11.0.18
#  environment:
#    JVM_OPTS: -Xmx3200m

orbs:
  android: circleci/android@2.2.0
  ruby: circleci/ruby@2.0.0

jobs:
  lint:
    executor:
      name: android/android-docker
      tag: 2022.12.1
    steps:
      - checkout
      - run:
          name: Create local properties
          command: |
            touch local.properties
            echo "apiKey=\"\"" >> local.properties
      - android/restore-gradle-cache
      - run: ./gradlew lintDebug
      - android/save-gradle-cache

  unit_test:
    executor:
      name: android/android-docker
      tag: 2022.12.1
    steps:
      - checkout
      - run:
          name: Create local properties
          command: |
            touch local.properties
            echo "apiKey=\"\"" >> local.properties
      - android/restore-gradle-cache
      - run: ./gradlew testDebugUnitTest
      - run:
          name: Install fastlane
          command: bundle install
      - run:
          name: Run the unit tests
          command: bundle exec fastlane test
      - android/save-gradle-cache
      - store_test_results:
          path: ./app/build/test-results/testDebugUnitTest

  integration_test:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.12.1
    steps:
      - checkout
      - run:
          name: Create local properties
          command: |
            touch local.properties
            echo "apiKey=\"\"" >> local.properties
      - android/start-emulator-and-run-tests
      - store_test_results:
          path: ./app/build/outputs/androidTest-results/connected

  build_for_integration_test:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.12.1
    steps:
      - checkout
      - run:
          name: Create local properties
          command: |
            touch local.properties
            echo "apiKey=\"\"" >> local.properties
      - android/restore-gradle-cache
      - run: ./gradlew assembleDebugAndroidTest
      - android/save-gradle-cache

  beta:
    executor:
      name: android/android-docker
      tag: 2022.12.1
    steps:
      - checkout
      - run:
          name: Create local properties
          command: |
            touch local.properties
            echo "apiKey=\"\"" >> local.properties
      - android/restore-gradle-cache
      - run:
          name: Install fastlane
          command: bundle install
      - run: bundle exec fastlane assemble_debug
      - run: bundle exec fastlane build
      - android/save-gradle-cache
#  build:
#    working_directory: ~/code
#    docker:
#      - image: cimg/openjdk:11.0.18
#    environment:
#      JVM_OPTS: -Xmx3200m
#    steps:
#      - checkout
#      - run:
#          name: Create local properties
#          command: |
#            touch local.properties
#            echo "apiKey=\"\"" >> local.properties
#      - run: java --version
#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      #      - run:
#      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#      #         command: sudo chmod +x ./gradlew
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          command: ruby/install-deps
#      - run:
#          name: Assemble a debug apk
#          command: bundle exec fastlane assemble_debug
#      - run:
#          name: Assemble an android test apk
#          command: bundle exec fastlane assemble_android_test
#      - run:
#          name: Build the aab file
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#      - store_test_results:
#          path: app/build/test-results
workflows:
  main:
    jobs:
      - lint
      - unit_test
      - integration_test
      - build_for_integration_test
      - beta
