name: Android CI

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master","develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Touch local properties
      run: touch local.properties
    - name: Add Api Key
      run: echo "apiKey=\"\"" >> local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
    - name: Run Tests
      run: ./gradlew test
